typography_spectrum: 0.9920224007219076
color:
  brandStrength: 0.26098680635914207
  lightness: 0.6547989279497415
  saturation: 0.8481612715404481
  rhythmicContrast: 0.5011580085847527
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.6793816641438752
analytics:
  google: UA-54466971-3
author:
  name: Jerry Spaeder
  email: jerry@spaeder.net
  url: 'http://spaeder.net'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bc6d00d2-e2f1-4b09-b5e6-8f8cb5e25a1e.jpg
name: Spaeder
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a29b69d-9803-4072-8bf9-da16acea8b01.jpg
title: Jerry Spaeder
description: ' '
