typography_spectrum: 0.7538059884682298
color:
  brandStrength: 0.21323483064770699
  lightness: 0.6779146969784051
  saturation: 0.635718890465796
  rhythmicContrast: 0.06790768099017441
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.7609926993027329
author:
  name: Jerry Spaeder
  email: jerry@spaeder.net
  url: spaeder.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bc6d00d2-e2f1-4b09-b5e6-8f8cb5e25a1e.jpg
name: Spaeder
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a29b69d-9803-4072-8bf9-da16acea8b01.jpg
title: Jerry Spaeder
description: ' '
